title: Jiafeng (Janice) Li
description: Statistical Analyst
site_title: '@JaniceLi'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: janiceli98315
blog_url: https://www.nagekar.com
email: janiceli98315@gmail.com


# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 
